In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

In [6]:
file_path = "E:/Banking-Transaction-Analysis/data/SFinDSet.csv"

df = pd.read_csv(file_path)

print("Dataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Dataset loaded successfully!
Rows: 1048575
Columns: 9

In [7]:
df.head()

,Transaction_ID,Account_Number,Account_Name,Transaction_Amount,Transaction_Mode,Transaction_Type,Transaction_Date,Transaction_Source,Transaction_Destination
0,TRANS-588469,9368326206,David Howard,1834602.80,Card Out,NGN to USD,10/28/2021 2:31,1698161104,20322866
1,TRANS-239018,6826045758,David Hughes,537724.40,Card Out,NGN to USD,8/31/2022 23:38,8172779956,20322866
2,TRANS-1949426,5386299916,David Huber,7875963.00,Card Out,NGN to USD,8/20/2023 8:56,3138972375,20322866
3,TRANS-1588193,1443563124,David Hunt,2007928.05,Card Out,NGN to USD,2/13/2023 16:14,9694080118,20322866
4,TRANS-224390,7244060183,David Hughes,47660283.50,Card Out,NGN to USD,3/21/2021 17:10,6225683619,20322866

In [8]:
df.tail()

,Transaction_ID,Account_Number,Account_Name,Transaction_Amount,Transaction_Mode,Transaction_Type,Transaction_Date,Transaction_Source,Transaction_Destination
1048570,TRANS-1040828,5186804614,William Gibson,2060870.6,Transfer Out,NGN to NGN,10/18/2023 16:14,1533886072,6641342145
1048571,TRANS-1040829,6731657350,Janice Harmon,28760240.5,Cash Out,NGN to NGN,12/29/2023 22:35,5634569137,5197504059
1048572,TRANS-1040830,1527677311,Kirsten Medina,1515022.0,Cash In,NGN to USD,9/16/2020 9:50,6317674933,5465800009
1048573,TRANS-1040831,5977782285,Anne Dennis,37523583.5,Cash Out,USD to USD,7/14/2021 15:44,4215281033,9726927462
1048574,TRANS-1040832,1391686672,Stephen Walsh,45899827.5,Transfer Out,USD to USD,1/19/2022 23:41,3215567501,6616440764

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 9 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   Transaction_ID           1048575 non-null  str
 1   Account_Number           1048575 non-null  int64
 2   Account_Name             1048575 non-null  str
 3   Transaction_Amount       1048575 non-null  float64
 4   Transaction_Mode         1048575 non-null  str
 5   Transaction_Type         1048575 non-null  str
 6   Transaction_Date         1048575 non-null  str
 7   Transaction_Source       1048575 non-null  int64
 8   Transaction_Destination  1048575 non-null  int64
dtypes: float64(1), int64(3), str(5)
memory usage: 130.9 MB

In [10]:
df.describe()

,Account_Number,Transaction_Amount,Transaction_Source,Transaction_Destination
count,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06
mean,4.998590e+09,1.376459e+07,4.998513e+09,4.998704e+09
std,2.886773e+09,1.522120e+07,2.886118e+09,2.885133e+09
min,5.000000e+02,1.005000e+02,1.259900e+04,4.959000e+03
25%,2.498664e+09,2.277421e+06,2.495615e+09,2.502691e+09
50%,4.998289e+09,4.549659e+06,4.997743e+09,4.999601e+09
75%,7.498337e+09,2.506618e+07,7.496419e+09,7.494183e+09
max,9.999995e+09,4.999995e+07,1.000000e+10,9.999998e+09

In [11]:
df.isnull().sum()

Transaction_ID             0
Account_Number             0
Account_Name               0
Transaction_Amount         0
Transaction_Mode           0
Transaction_Type           0
Transaction_Date           0
Transaction_Source         0
Transaction_Destination    0
dtype: int64

In [15]:
df['Transaction_Mode'].value_counts()

Transaction_Mode
Card Out        215909
Cash Out        208424
Transfer In     208315
Transfer Out    208228
Cash In         207699
Name: count, dtype: int64

In [16]:
df['Transaction_Type'].value_counts()

Transaction_Type
NGN to USD    267515
USD to USD    260526
NGN to NGN    260429
USD to NGN    260105
Name: count, dtype: int64

In [17]:
df['Account_Number'].nunique()

1044443

In [18]:
df['Transaction_Source'].nunique()

1044454

In [19]:
df['Transaction_Date'] = pd.to_datetime(
    df['Transaction_Date'],
    errors='coerce'
)

In [20]:
df['Transaction_Date'].dtype

dtype('<M8[us]')

In [21]:
df['Transaction_Date'].isna().sum()

np.int64(0)

In [22]:
print("Minimum date:", df['Transaction_Date'].min())
print("Maximum date:", df['Transaction_Date'].max())

Minimum date: 2020-01-01 00:01:00
Maximum date: 2024-02-18 12:24:00

In [24]:
df['Year'] = df['Transaction_Date'].dt.year
df['Month'] = df['Transaction_Date'].dt.month
df['Month_Name'] = df['Transaction_Date'].dt.month_name()
df['Day'] = df['Transaction_Date'].dt.day
df['Hour'] = df['Transaction_Date'].dt.hour
df['Day_Name'] = df['Transaction_Date'].dt.day_name()

In [25]:
print("Columns:", df.shape[1])

Columns: 15

In [26]:
df.head()

,Transaction_ID,Account_Number,Account_Name,Transaction_Amount,Transaction_Mode,Transaction_Type,Transaction_Date,Transaction_Source,Transaction_Destination,Year,Month,Month_Name,Day,Hour,Day_Name
0,TRANS-588469,9368326206,David Howard,1834602.80,Card Out,NGN to USD,2021-10-28 02:31:00,1698161104,20322866,2021,10,October,28,2,Thursday
1,TRANS-239018,6826045758,David Hughes,537724.40,Card Out,NGN to USD,2022-08-31 23:38:00,8172779956,20322866,2022,8,August,31,23,Wednesday
2,TRANS-1949426,5386299916,David Huber,7875963.00,Card Out,NGN to USD,2023-08-20 08:56:00,3138972375,20322866,2023,8,August,20,8,Sunday
3,TRANS-1588193,1443563124,David Hunt,2007928.05,Card Out,NGN to USD,2023-02-13 16:14:00,9694080118,20322866,2023,2,February,13,16,Monday
4,TRANS-224390,7244060183,David Hughes,47660283.50,Card Out,NGN to USD,2021-03-21 17:10:00,6225683619,20322866,2021,3,March,21,17,Sunday

In [27]:
df.duplicated().sum()

np.int64(109)

In [28]:
df = df.drop_duplicates().copy()

In [29]:
df.duplicated().sum()

np.int64(0)

In [32]:
df.shape

(1048466, 15)

In [33]:
df['Transaction_Amount'].describe()

count    1.048466e+06
mean     1.376450e+07
std      1.522120e+07
min      1.005000e+02
25%      2.277357e+06
50%      4.549606e+06
75%      2.506616e+07
max      4.999995e+07
Name: Transaction_Amount, dtype: float64

In [34]:
percentiles = df['Transaction_Amount'].quantile(
    [0.50, 0.75, 0.90, 0.95, 0.99, 0.999]
)

percentiles

0.500    4.549606e+06
0.750    2.506616e+07
0.900    3.994727e+07
0.950    4.499646e+07
0.990    4.899112e+07
0.999    4.990104e+07
Name: Transaction_Amount, dtype: float64

In [35]:
print ("Statistical Analysis")

Statistical Analysis

In [36]:
p99 = df['Transaction_Amount'].quantile(0.99)

print("99th Percentile:", p99)

99th Percentile: 48991120.05

In [38]:
high_value_transactions = df[
    df['Transaction_Amount'] > p99
].copy()

In [39]:
len(high_value_transactions)

10485

In [40]:
high_value_transactions[
    [
        'Transaction_ID',
        'Account_Number',
        'Transaction_Amount',
        'Transaction_Mode',
        'Transaction_Type',
        'Transaction_Date'
    ]
].head(10)

,Transaction_ID,Account_Number,Transaction_Amount,Transaction_Mode,Transaction_Type,Transaction_Date
28,TRANS-1789885,60013805,49362645.0,Card Out,NGN to USD,2020-05-02 17:54:00
86,TRANS-1541814,3104776600,49252955.0,Card Out,NGN to USD,2020-05-05 07:54:00
193,TRANS-60181,5856839653,49744831.0,Card Out,NGN to USD,2021-03-11 17:59:00
258,TRANS-1712875,754411736,49783022.5,Card Out,NGN to USD,2021-11-05 14:54:00
304,TRANS-1113331,574352100,49370862.5,Card Out,NGN to USD,2022-02-13 07:16:00
324,TRANS-650219,7821044369,49367712.5,Card Out,NGN to USD,2023-09-06 01:55:00
364,TRANS-33150,2247942867,49991231.5,Card Out,NGN to USD,2020-09-25 14:37:00
467,TRANS-815883,8193414788,49677031.0,Card Out,NGN to USD,2023-10-14 16:26:00
517,TRANS-1821440,2838757302,49903087.5,Card Out,NGN to USD,2020-09-06 23:08:00
572,TRANS-446107,9991460054,49464002.5,Card Out,NGN to USD,2020-10-11 17:40:00

In [41]:
print("Calculate IQR")
Q1 = df['Transaction_Amount'].quantile(0.25)
Q3 = df['Transaction_Amount'].quantile(0.75)

IQR = Q3 - Q1

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)

Calculate IQR
Q1: 2277357.0749999997
Q3: 25066160.125
IQR: 22788803.05

In [42]:
upper_bound = Q3 + 1.5 * IQR

print("Upper Outlier Bound:", upper_bound)

Upper Outlier Bound: 59249364.7

In [43]:
print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Upper Outlier Bound:", upper_bound)

Q1: 2277357.0749999997
Q3: 25066160.125
IQR: 22788803.05
Upper Outlier Bound: 59249364.7

In [44]:
account_activity = (
    df.groupby('Account_Number')
      .agg(
          Transaction_Count=('Transaction_ID', 'count'),
          Total_Amount=('Transaction_Amount', 'sum'),
          Average_Amount=('Transaction_Amount', 'mean')
      )
      .sort_values('Transaction_Count', ascending=False)
)

account_activity.head(10)

                Transaction_Count  Total_Amount  Average_Amount
Account_Number
4645947792                      2    17126248.0      8563124.00
169186487                       2      648978.8       324489.40
2083811173                      2    26033162.0     13016581.00
2215393909                      2     5387992.3      2693996.15
18650790                        2    60412119.0     30206059.50
4610210368                      2     9951560.6      4975780.30
1871116943                      2     7929608.0      3964804.00
3683262253                      2    65978931.0     32989465.50
3442203476                      2    54184060.0     27092030.00
4914913757                      2    51250619.0     25625309.50

In [45]:
top_accounts_by_amount = (
    account_activity
    .sort_values('Total_Amount', ascending=False)
)

top_accounts_by_amount.head(10)

                Transaction_Count  Total_Amount  Average_Amount
Account_Number
2247942867                      2    99982463.0      49991231.5
8499158133                      2    99956595.0      49978297.5
6796681714                      2    99951853.0      49975926.5
4947871623                      2    99891904.0      49945952.0
4793408787                      2    99863876.0      49931938.0
1915856774                      2    99789960.0      49894980.0
5340540258                      2    99756622.0      49878311.0
5259739721                      2    99723721.0      49861860.5
1164246511                      2    99653828.0      49826914.0
6731593306                      2    99627661.0      49813830.5

In [46]:
route_counts = (
    df.groupby(['Transaction_Source', 'Transaction_Destination'])
      .size()
      .reset_index(name='Transaction_Count')
      .sort_values('Transaction_Count', ascending=False)
)

route_counts.head(10)

   Transaction_Source  Transaction_Destination  Transaction_Count
0               12599               2657153089                  1
1               23810               4073440094                  1
2               28461               9212328628                  1
3               39269               5943872208                  1
4               55245               8513722728                  1
5               66537               8159668603                  1
6               80707               8231953881                  1
7              156318               2396291311                  1
8              219277               3409721970                  1
9              223313               6345212315                  1

In [47]:
mode_type_analysis = (
    df.groupby(['Transaction_Mode', 'Transaction_Type'])
      .agg(
          Transaction_Count=('Transaction_ID', 'count'),
          Total_Amount=('Transaction_Amount', 'sum'),
          Average_Amount=('Transaction_Amount', 'mean')
      )
      .sort_values('Transaction_Count', ascending=False)
)

mode_type_analysis

                                   Transaction_Count  Total_Amount  \
Transaction_Mode Transaction_Type
Card Out         NGN to USD                    59924  8.278420e+11
Cash In          NGN to USD                    52503  7.210756e+11
Transfer Out     USD to NGN                    52371  7.214280e+11
Cash Out         NGN to NGN                    52323  7.229257e+11
Transfer In      NGN to NGN                    52286  7.217763e+11
                 USD to USD                    52269  7.186539e+11
Transfer Out     USD to USD                    52197  7.236295e+11
Transfer In      USD to NGN                    52183  7.124934e+11
Cash Out         USD to USD                    52159  7.197176e+11
                 USD to NGN                    52159  7.111018e+11
Transfer Out     NGN to NGN                    52041  7.148373e+11
Card Out         USD to USD                    52024  7.152880e+11
                 NGN to NGN                    52005  7.117318e+11
Cash In          USD to USD                    51877  7.145830e+11
Card Out         USD to NGN                    51847  7.141681e+11
Cash Out         NGN to USD                    51783  7.077987e+11
Cash In          NGN to NGN                    51774  7.109813e+11
Transfer Out     NGN to USD                    51619  7.207257e+11
Transfer In      NGN to USD                    51577  7.104459e+11
Cash In          USD to NGN                    51545  7.104103e+11

                                   Average_Amount
Transaction_Mode Transaction_Type
Card Out         NGN to USD          1.381487e+07
Cash In          NGN to USD          1.373399e+07
Transfer Out     USD to NGN          1.377533e+07
Cash Out         NGN to NGN          1.381660e+07
Transfer In      NGN to NGN          1.380439e+07
                 USD to USD          1.374914e+07
Transfer Out     USD to USD          1.386343e+07
Transfer In      USD to NGN          1.365375e+07
Cash Out         USD to USD          1.379853e+07
                 USD to NGN          1.363335e+07
Transfer Out     NGN to NGN          1.373604e+07
Card Out         USD to USD          1.374919e+07
                 NGN to NGN          1.368583e+07
Cash In          USD to USD          1.377456e+07
Card Out         USD to NGN          1.377453e+07
Cash Out         NGN to USD          1.366855e+07
Cash In          NGN to NGN          1.373240e+07
Transfer Out     NGN to USD          1.396241e+07
Transfer In      NGN to USD          1.377447e+07
Cash In          USD to NGN          1.378233e+07

In [48]:
hourly_activity = (
    df.groupby('Hour')
      .agg(
          Transaction_Count=('Transaction_ID', 'count'),
          Total_Amount=('Transaction_Amount', 'sum'),
          Average_Amount=('Transaction_Amount', 'mean')
      )
      .sort_index()
)

hourly_activity

      Transaction_Count  Total_Amount  Average_Amount
Hour
0                 43710  6.071616e+11    1.389068e+07
1                 43782  5.981939e+11    1.366301e+07
2                 43313  5.947902e+11    1.373237e+07
3                 43537  6.012780e+11    1.381074e+07
4                 44038  6.087248e+11    1.382272e+07
5                 43561  6.023223e+11    1.382710e+07
6                 43568  5.989777e+11    1.374811e+07
7                 43946  6.037305e+11    1.373801e+07
8                 43561  5.991675e+11    1.375468e+07
9                 43796  5.965915e+11    1.362205e+07
10                43780  6.017877e+11    1.374572e+07
11                44007  6.021769e+11    1.368366e+07
12                43161  5.913512e+11    1.370105e+07
13                43401  5.993998e+11    1.381074e+07
14                43681  5.981157e+11    1.369281e+07
15                44042  6.063806e+11    1.376824e+07
16                43768  5.968734e+11    1.363721e+07
17                43661  6.078010e+11    1.392091e+07
18                43670  6.050741e+11    1.385560e+07
19                43602  5.988320e+11    1.373405e+07
20                43623  5.999302e+11    1.375261e+07
21                43737  5.999342e+11    1.371686e+07
22                44030  6.079003e+11    1.380650e+07
23                43491  6.051188e+11    1.391366e+07

In [49]:
day_analysis = (
    df.groupby('Day_Name')
      .agg(
          Transaction_Count=('Transaction_ID', 'count'),
          Total_Amount=('Transaction_Amount', 'sum'),
          Average_Amount=('Transaction_Amount', 'mean')
      )
)

day_analysis

           Transaction_Count  Total_Amount  Average_Amount
Day_Name
Friday                149726  2.062102e+12    1.377250e+07
Monday                149565  2.043607e+12    1.366367e+07
Saturday              150215  2.068849e+12    1.377259e+07
Sunday                149818  2.073213e+12    1.383821e+07
Thursday              150064  2.071386e+12    1.380335e+07
Tuesday               149618  2.058053e+12    1.375539e+07
Wednesday             149460  2.054404e+12    1.374551e+07

In [50]:
monthly_analysis = (
    df.groupby(['Year', 'Month', 'Month_Name'])
      .agg(
          Transaction_Count=('Transaction_ID', 'count'),
          Total_Amount=('Transaction_Amount', 'sum'),
          Average_Amount=('Transaction_Amount', 'mean')
      )
      .reset_index()
      .sort_values(['Year', 'Month'])
)

monthly_analysis

    Year  Month Month_Name  Transaction_Count  Total_Amount  Average_Amount
0   2020      1    January              21565  2.948956e+11    1.367473e+07
1   2020      2   February              20247  2.747616e+11    1.357049e+07
2   2020      3      March              21912  3.022657e+11    1.379453e+07
3   2020      4      April              20927  2.908092e+11    1.389636e+07
4   2020      5        May              21432  2.971390e+11    1.386427e+07
5   2020      6       June              20760  2.870000e+11    1.382467e+07
6   2020      7       July              21508  2.895252e+11    1.346128e+07
7   2020      8     August              21443  2.930976e+11    1.366868e+07
8   2020      9  September              20891  2.860854e+11    1.369420e+07
9   2020     10    October              21721  2.969157e+11    1.366952e+07
10  2020     11   November              20710  2.797183e+11    1.350644e+07
11  2020     12   December              21536  2.994469e+11    1.390448e+07
12  2021      1    January              21455  2.930474e+11    1.365870e+07
13  2021      2   February              19633  2.693677e+11    1.372015e+07
14  2021      3      March              21521  2.964352e+11    1.377423e+07
15  2021      4      April              20937  2.867693e+11    1.369677e+07
16  2021      5        May              21390  2.945854e+11    1.377211e+07
17  2021      6       June              20525  2.783159e+11    1.355985e+07
18  2021      7       July              21597  2.977971e+11    1.378882e+07
19  2021      8     August              21527  3.003315e+11    1.395139e+07
20  2021      9  September              20806  2.869115e+11    1.378984e+07
21  2021     10    October              21534  2.952370e+11    1.371027e+07
22  2021     11   November              20716  2.871787e+11    1.386265e+07
23  2021     12   December              21861  3.044185e+11    1.392518e+07
24  2022      1    January              21700  2.975556e+11    1.371224e+07
25  2022      2   February              19507  2.728114e+11    1.398531e+07
26  2022      3      March              21465  2.955207e+11    1.376756e+07
27  2022      4      April              20866  2.880066e+11    1.380268e+07
28  2022      5        May              21684  2.989782e+11    1.378796e+07
29  2022      6       June              20900  2.878736e+11    1.377386e+07
30  2022      7       July              21616  2.957018e+11    1.367976e+07
31  2022      8     August              21731  2.981842e+11    1.372161e+07
32  2022      9  September              20818  2.835952e+11    1.362259e+07
33  2022     10    October              21544  2.950021e+11    1.369300e+07
34  2022     11   November              20724  2.875073e+11    1.387316e+07
35  2022     12   December              21535  2.953527e+11    1.371501e+07
36  2023      1    January              21659  2.938278e+11    1.356608e+07
37  2023      2   February              19370  2.646236e+11    1.366152e+07
38  2023      3      March              21498  2.983999e+11    1.388036e+07
39  2023      4      April              20703  2.872112e+11    1.387293e+07
40  2023      5        May              21338  2.949352e+11    1.382207e+07
41  2023      6       June              20674  2.848429e+11    1.377783e+07
42  2023      7       July              21635  3.001311e+11    1.387248e+07
43  2023      8     August              21318  2.952700e+11    1.385074e+07
44  2023      9  September              20693  2.870016e+11    1.386950e+07
45  2023     10    October              21325  2.953530e+11    1.385008e+07
46  2023     11   November              20842  2.918268e+11    1.400186e+07
47  2023     12   December              21421  2.948640e+11    1.376518e+07
48  2024      1    January              21520  2.956407e+11    1.373795e+07
49  2024      2   February              12226  1.695412e+11    1.386726e+07

In [51]:
mode_analysis = (
    df.groupby('Transaction_Mode')
      .agg(
          Transaction_Count=('Transaction_ID', 'count'),
          Total_Amount=('Transaction_Amount', 'sum'),
          Average_Amount=('Transaction_Amount', 'mean')
      )
      .sort_values('Transaction_Count', ascending=False)
)

mode_analysis

                  Transaction_Count  Total_Amount  Average_Amount
Transaction_Mode
Card Out                     215800  2.969030e+12    1.375825e+07
Cash Out                     208424  2.861544e+12    1.372944e+07
Transfer In                  208315  2.863369e+12    1.374538e+07
Transfer Out                 208228  2.880621e+12    1.383397e+07
Cash In                      207699  2.857050e+12    1.375572e+07

In [52]:
type_analysis = (
    df.groupby('Transaction_Type')
      .agg(
          Transaction_Count=('Transaction_ID', 'count'),
          Total_Amount=('Transaction_Amount', 'sum'),
          Average_Amount=('Transaction_Amount', 'mean')
      )
      .sort_values('Transaction_Count', ascending=False)
)

type_analysis

                  Transaction_Count  Total_Amount  Average_Amount
Transaction_Type
NGN to USD                   267406  3.687888e+12    1.379134e+07
USD to USD                   260526  3.591872e+12    1.378700e+07
NGN to NGN                   260429  3.582252e+12    1.375520e+07
USD to NGN                   260105  3.569601e+12    1.372369e+07

In [53]:
high_value_profile = (
    high_value_transactions
    .groupby(['Transaction_Mode', 'Transaction_Type'])
    .agg(
        Transaction_Count=('Transaction_ID', 'count'),
        Total_Amount=('Transaction_Amount', 'sum'),
        Average_Amount=('Transaction_Amount', 'mean')
    )
    .sort_values('Transaction_Count', ascending=False)
)

high_value_profile

                                   Transaction_Count  Total_Amount  \
Transaction_Mode Transaction_Type
Card Out         NGN to USD                      633  3.132704e+10
Transfer Out     USD to NGN                      565  2.796912e+10
Cash In          USD to NGN                      554  2.741201e+10
Transfer Out     NGN to NGN                      537  2.658338e+10
Cash In          NGN to NGN                      530  2.623303e+10
Card Out         USD to NGN                      527  2.607854e+10
Cash In          USD to USD                      526  2.604829e+10
Transfer In      NGN to NGN                      524  2.594498e+10
                 USD to USD                      524  2.593779e+10
Cash In          NGN to USD                      523  2.589382e+10
Cash Out         NGN to NGN                      522  2.583776e+10
Card Out         NGN to NGN                      521  2.578547e+10
Cash Out         USD to NGN                      521  2.579332e+10
                 NGN to USD                      517  2.558248e+10
Transfer In      NGN to USD                      515  2.549015e+10
Transfer Out     USD to USD                      513  2.540030e+10
Cash Out         USD to USD                      508  2.514841e+10
Transfer Out     NGN to USD                      502  2.484816e+10
Card Out         USD to USD                      471  2.330963e+10
Transfer In      USD to NGN                      452  2.237114e+10

                                   Average_Amount
Transaction_Mode Transaction_Type
Card Out         NGN to USD          4.948979e+07
Transfer Out     USD to NGN          4.950288e+07
Cash In          USD to NGN          4.948016e+07
Transfer Out     NGN to NGN          4.950350e+07
Cash In          NGN to NGN          4.949628e+07
Card Out         USD to NGN          4.948489e+07
Cash In          USD to USD          4.952147e+07
Transfer In      NGN to NGN          4.951333e+07
                 USD to USD          4.949960e+07
Cash In          NGN to USD          4.951017e+07
Cash Out         NGN to NGN          4.949762e+07
Card Out         NGN to NGN          4.949226e+07
Cash Out         USD to NGN          4.950734e+07
                 NGN to USD          4.948255e+07
Transfer In      NGN to USD          4.949543e+07
Transfer Out     USD to USD          4.951326e+07
Cash Out         USD to USD          4.950474e+07
Transfer Out     NGN to USD          4.949833e+07
Card Out         USD to USD          4.948966e+07
Transfer In      USD to NGN          4.949368e+07

In [54]:
account_stats = (
    df.groupby('Account_Number')
      .agg(
          Transaction_Count=('Transaction_ID', 'count'),
          Total_Amount=('Transaction_Amount', 'sum'),
          Average_Amount=('Transaction_Amount', 'mean')
      )
      .reset_index()
)

account_stats.head()

   Account_Number  Transaction_Count  Total_Amount  Average_Amount
0             500                  1    24341223.5      24341223.5
1            5428                  1      952690.1        952690.1
2           17363                  1     4367354.1       4367354.1
3           22169                  1     3161369.0       3161369.0
4           29334                  1    33254781.0      33254781.0

In [55]:
account_amount_p99 = account_stats['Total_Amount'].quantile(0.99)

print("Account Total Amount P99:", account_amount_p99)

Account Total Amount P99: 49085225.89

In [56]:
high_value_accounts = account_stats[
    account_stats['Total_Amount'] > account_amount_p99
].copy()

print("High-Value Accounts:", len(high_value_accounts))

High-Value Accounts: 10445

In [58]:
df['High_Value_Flag'] = (
    df['Transaction_Amount'] > p99
).astype(int)

In [59]:
df['Risk_Score'] = df['High_Value_Flag']

df['Risk_Level'] = df['Risk_Score'].map({
    0: 'Low',
    1: 'High'
})

In [60]:
risk_summary = (
    df['Risk_Level']
      .value_counts()
      .reset_index()
)

risk_summary.columns = ['Risk_Level', 'Transaction_Count']

risk_summary

  Risk_Level  Transaction_Count
0        Low            1037981
1       High              10485

In [61]:
# Save the final cleaned dataset for MySQL and Power BI
output_path = "E:/Banking-Transaction-Analysis/data/cleaned_banking_transactions.csv"

df.to_csv(output_path, index=False)

print("Final cleaned dataset saved successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("File:", output_path)

Final cleaned dataset saved successfully!
Rows: 1048466
Columns: 18
File: E:/Banking-Transaction-Analysis/data/cleaned_banking_transactions.csv

In [63]:
df.head()

,Transaction_ID,Account_Number,Account_Name,Transaction_Amount,Transaction_Mode,Transaction_Type,Transaction_Date,Transaction_Source,Transaction_Destination,Year,Month,Month_Name,Day,Hour,Day_Name,High_Value_Flag,Risk_Score,Risk_Level
0,TRANS-588469,9368326206,David Howard,1834602.80,Card Out,NGN to USD,2021-10-28 02:31:00,1698161104,20322866,2021,10,October,28,2,Thursday,0,0,Low
1,TRANS-239018,6826045758,David Hughes,537724.40,Card Out,NGN to USD,2022-08-31 23:38:00,8172779956,20322866,2022,8,August,31,23,Wednesday,0,0,Low
2,TRANS-1949426,5386299916,David Huber,7875963.00,Card Out,NGN to USD,2023-08-20 08:56:00,3138972375,20322866,2023,8,August,20,8,Sunday,0,0,Low
3,TRANS-1588193,1443563124,David Hunt,2007928.05,Card Out,NGN to USD,2023-02-13 16:14:00,9694080118,20322866,2023,2,February,13,16,Monday,0,0,Low
4,TRANS-224390,7244060183,David Hughes,47660283.50,Card Out,NGN to USD,2021-03-21 17:10:00,6225683619,20322866,2021,3,March,21,17,Sunday,0,0,Low
5,TRANS-1239929,9633854457,Howard Johnson,1150287.95,Card Out,NGN to USD,2023-06-03 19:02:00,7868253594,20322866,2023,6,June,3,19,Saturday,0,0,Low
6,TRANS-1947599,386730764,Holly Williams,1139611.40,Card Out,NGN to USD,2022-03-19 20:28:00,4144644182,20322866,2022,3,March,19,20,Saturday,0,0,Low
7,TRANS-681022,4839114133,Holly Williams,2735754.80,Card Out,NGN to USD,2021-11-24 23:57:00,1982566656,20322866,2021,11,November,24,23,Wednesday,0,0,Low
8,TRANS-1982400,558229106,Holly Torres,3814374.10,Card Out,NGN to USD,2022-08-06 20:35:00,4413396848,20322866,2022,8,August,6,20,Saturday,0,0,Low
9,TRANS-501475,7065199105,David Howard,3058606.95,Card Out,NGN to USD,2020-11-15 04:57:00,531803346,20322866,2020,11,November,15,4,Sunday,0,0,Low
10,TRANS-783369,8037908685,Holly Torres,3577399.05,Card Out,NGN to USD,2020-06-25 22:26:00,3215349112,20322866,2020,6,June,25,22,Thursday,0,0,Low
11,TRANS-606894,5116002507,Holly Spencer,2680621.60,Card Out,NGN to USD,2022-05-29 10:26:00,8217796508,20322866,2022,5,May,29,10,Sunday,0,0,Low
12,TRANS-1083123,3805493965,Holly Smith,2370679.60,Card Out,NGN to USD,2021-01-16 07:59:00,4435012688,20322866,2021,1,January,16,7,Saturday,0,0,Low
13,TRANS-1706662,9077766167,Holly Smith,44771957.00,Card Out,NGN to USD,2020-06-09 01:36:00,1382384927,20322866,2020,6,June,9,1,Tuesday,0,0,Low
14,TRANS-953163,1811779569,Holly Smith,2405418.40,Card Out,NGN to USD,2020-10-16 04:54:00,3002565038,20322866,2020,10,October,16,4,Friday,0,0,Low
15,TRANS-1077931,7429436636,David Hughes,45818587.50,Card Out,NGN to USD,2021-06-27 02:29:00,9007354067,20322866,2021,6,June,27,2,Sunday,0,0,Low
16,TRANS-249176,951609076,David Hughes,10690148.00,Card Out,NGN to USD,2020-09-06 13:21:00,2110114123,20322866,2020,9,September,6,13,Sunday,0,0,Low
17,TRANS-1131105,1837206255,Holly Spencer,21283976.00,Card Out,NGN to USD,2022-04-02 11:16:00,43565969,20322866,2022,4,April,2,11,Saturday,0,0,Low
18,TRANS-1785394,7579157459,David Hunt,4139932.40,Card Out,NGN to USD,2021-10-04 15:45:00,6269743644,20322866,2021,10,October,4,15,Monday,0,0,Low
19,TRANS-1480913,5139577318,David Huber,3411150.15,Card Out,NGN to USD,2020-07-03 06:10:00,4034402924,20322866,2020,7,July,3,6,Friday,0,0,Low